// Code generated by probe-registry-gen. DO NOT EDIT.
//go:generate go run ../../../cmd/probe-registry-gen

// Package registry 自动导入所有探针包以触发 init() 注册
package registry

import (
	_ "ebpf-mcp/ebpf/NFS-client/nfs_file_read"
)

// init 确保所有探针的 init() 函数已被调用
func init() {
	// 探针通过各自的 init() 函数自动注册到 probes.registry
}
